force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Hours_Sold__c.field-meta.xml
<CustomField>
    <fullName>Hours_Sold__c</fullName>
    <label>Hours Sold</label>
    <summarizedField>Project_Role__c.Hours_Required__c</summarizedField>
    <summaryForeignKey>Project_Role__c.Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-kickoff</fullName>
                <default>true</default>
                <label>Pre-kickoff</label>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Role__c/Project_Role__c.object-meta.xml
<CustomObject>
    <label>Project Role</label>
    <nameField>
        <displayFormat>ROLE-{0000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Role__c/fields/Hours_Covered__c.field-meta.xml
<CustomField>
    <fullName>Hours_Covered__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Hours Covered</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Hours_Required__c.field-meta.xml
<CustomField>
    <fullName>Hours_Required__c</fullName>
    <label>Hours Required</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Role__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <formula>2+2</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectDataService.cls
public without sharing class ProjectDataService {

    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProjectRolesRequired(Id projectId) {
        System.debug(projectId);

        List<Project__c> projectRolesRequired = [
            SELECT Name, Start_Date__c, End_Date__c, Hours_Sold__c, Status__c,
                (
                    SELECT Hours_Covered__c, Hours_Required__c, Role__c 
                    FROM Roles__r
                    ORDER BY Role__c DESC
                )
            FROM Project__c
            WHERE Id = :projectId
        ];

        System.debug(projectId);
        System.debug(projectRolesRequired);
        return projectRolesRequired;
    }


    @AuraEnabled(cacheable=false)
    public static List<Resource__c> getAssignedResources(Id projectId) {
        List<Resource__c> assignedResList = [
            SELECT Id, User__r.Name, Start_Date__c, End_Date__c, Hours__c, Role__c 
            FROM Resource__c 
            WHERE Project__c = :projectId
            ORDER BY Role__c DESC
        ];
        return assignedResList;
    }


    @AuraEnabled(cacheable=false)
    public static List<User> getUsersAvailableForProject(Date startDate, Date endDate, List<String> roleList) {

        system.debug(startDate);
        system.debug(endDate);
        List<Resource__c> resourcesInProjects = [
            SELECT User__c, User__r.Name // Id, Name, Start_Date__c, End_Date__c 
            FROM Resource__c 
            WHERE ((Start_Date__c <= :startDate) AND (End_Date__c >= :startDate))
					OR ((Start_Date__c <= :endDate) AND (End_Date__c >= :endDate))
				OR
					((Start_Date__c >= :startDate) AND (End_Date__c <= :endDate))
                    
        ];
        System.debug(resourcesInProjects);

        List<Id> usersIdNOTAvailable = new List<Id>();             
        for (Resource__c res : resourcesInProjects) {
            usersIdNOTAvailable.add(res.User__c);
            System.debug(res.User__c);
            System.debug(res.User__r.Name);
        }
        System.debug(usersIdNOTAvailable);

        List<User> availableUsersForProject = [
            SELECT Id, Name, UserRole.Name //, (SELECT Start_Date__c, End_Date__c FROM Resources__r WHERE NOT ((Start_Date__c >= :endDate) OR (End_Date__c <= :startDate)))
            FROM User
            WHERE (Id NOT IN :usersIdNOTAvailable) AND (UserRole.Name IN :roleList)
            ORDER BY UserRole.Name DESC
        ];
        System.debug(availableUsersForProject);

        return availableUsersForProject;
    }

    @AuraEnabled(cacheable=false)
    public static List<Resource__c> insertResourcesToProject(Id projectId, List<List<String>> users) { //  Date startDate, Date endDate,
        List<Resource__c> resources = new List<Resource__c>();

        for (List<String> user : users) {
            Resource__c resource = new Resource__c(
                Project__c = projectId,
                User__c = user[0],
                Role__c = user[1],
                Start_Date__c = date.valueOf(user[2]),
                End_Date__c = date.valueOf(user[3]),
                Hours__c = integer.valueOf(user[4])
            );
            resources.add(resource);
        }

        try {
            insert(resources);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }

        return resources;
    }

}