force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>PRJ-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <label>Resource</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Resource Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Resources</relationshipLabel>
    <relationshipName>Resources</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectDataServiceTest.cls
@isTest
public with sharing class ProjectDataServiceTest {


    @isTest static void testAssignedResourcesQuantity() {
        // Test data setup
        Resource__c[] rsc = TestDataFactory.createResource(6, '14/3/2023', '15/3/2023', 'Developer'); 
        List<Project__c> lss = [SELECT ID FROM Project__c];    
        // Perform test
        Test.startTest();
		List<Resource__c> result = new List<Resource__c>();   
        for(Project__c res : lss) {
            result = ProjectDataService.getAssignedResources(res.Id);
        }     
        Test.stopTest();
        // Verify 
        System.assertEquals(6, result.size());
    }


}